"""Shared scientific and scan defaults for every Python entry point."""

DEFAULT_SCALED_MUTATION_RATE = 0.00075
DEFAULT_RECOMBINATION_TO_MUTATION_RATIO = 0.8
DEFAULT_MUTATION_RATE = 1.29e-9
DEFAULT_OUTPUT_STRIDE = 10_000
DEFAULT_CACHE_SIZE = 1_000
DEFAULT_GENERATION_TIME = 25
